version: '3.1'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis
    ports:
      - "5432:27017"
    volumes:
      - /home/davi/puc/gces/tp-individual-gces/Docker/Volumes/MongoDB:/data/db
    networks:
      - puc-gces-py

networks: 
    puc-gces-py:
      driver: bridge